FROM php:8.3-fpm

# システムパッケージとPHP拡張のインストール
RUN apt-get update && apt-get install -y \
  git \
  curl \
  libpng-dev \
  libonig-dev \
  libxml2-dev \
  libzip-dev \
  zip \
  unzip \
  vim \
  && docker-php-ext-install zip bcmath mbstring

# Node.jsとnpmのインストール
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash - \
  && apt-get install -y nodejs

# Composerのインストール
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# 作業ディレクトリの設定
WORKDIR /app

# プロジェクトファイルをコピー
COPY . .

# Composer依存関係のインストール
RUN if [ -f "composer.json" ]; then composer install --no-interaction --no-plugins --no-scripts --prefer-dist; fi

# npmパッケージのインストール
RUN if [ -f "package.json" ]; then npm install; fi

# PHP-FPMの実行
CMD ["php-fpm"]